### ISSUE TITLE
Função bucket.ListURLs() está retornando panic.

### ISSUE THREAD

**Issue by ArthurSpeziali** [meunomeebero/h-virus#1]
Projeto compilado, quando tentei executalo, retornou este seguinte erro:

panic: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListObjectsV2Input.Bucket.

goroutine 1 [running]:
github.com/robertokbr/hvirus/bucket.ListURLs()
	/home/arthur/Gits/h-virus/bucket/bucket.go:36 +0x392
main.main()
	/home/arthur/Gits/h-virus/main.go:24 +0x1f
exit status 2

Fica a pergunta, como não manjo de golang... o erro é vindo da api da Aws?
Mesmo o projeto não sido atualiza a 6 messes e tendo 1 commit, da esta atençãozinha aí 🥺️

**Comment by meunomeebero** [comment]
> Projeto compilado, quando tentei executalo, retornou este seguinte erro:
> 
> panic: InvalidParameter: 1 validation error(s) found.
> 
> * minimum field size of 1, ListObjectsV2Input.Bucket.
> 
> goroutine 1 [running]: github.com/robertokbr/hvirus/bucket.ListURLs() /home/arthur/Gits/h-virus/bucket/bucket.go:36 +0x392 main.main() /home/arthur/Gits/h-virus/main.go:24 +0x1f exit status 2
> 
> Fica a pergunta, como não manjo de golang... o erro é vindo da api da Aws? Mesmo o projeto não sido atualiza a 6 messes e tendo 1 commit, da esta atençãozinha aí 🥺️

KKKKKKKKKK pode deixar meu mano. eu vou fazer esse fix (vou dar suporte para que vcs possam usar seus proprios buckets antes de compilar). E sim, o problema é da AWS, o binário que eu deixar compilado no releases aponta pra um bucket gratuito que o mano Jeff Bezos já madou de arrasta

**Comment by ArthurSpeziali** [comment]
> > Projeto compilado, quando tentei executalo, retornou este seguinte erro:
> > panic: InvalidParameter: 1 validation error(s) found.
> > 
> > * minimum field size of 1, ListObjectsV2Input.Bucket.
> > 
> > goroutine 1 [running]: github.com/robertokbr/hvirus/bucket.ListURLs() /home/arthur/Gits/h-virus/bucket/bucket.go:36 +0x392 main.main() /home/arthur/Gits/h-virus/main.go:24 +0x1f exit status 2
> > Fica a pergunta, como não manjo de golang... o erro é vindo da api da Aws? Mesmo o projeto não sido atualiza a 6 messes e tendo 1 commit, da esta atençãozinha aí 🥺️
> 
> KKKKKKKKKK pode deixar meu mano. eu vou fazer esse fix (vou dar suporte para que vcs possam usar seus proprios buckets antes de compilar). E sim, o problema é da AWS, o binário que eu deixar compilado no releases aponta pra um bucket gratuito que o mano Jeff Bezos já madou de arrasta

Valeu cara, nunca é demais dar uma atenção para projetos nobres, como este
